---
title: "Obligatory Assignment 3"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r main, warning = FALSE, echo = FALSE, message = FALSE}
library(readr)
install.packages("dplyr")
install.packages("contrib.url")


#Laster inn data
by_county <- read_delim("http://data.ssb.no/api/v0/dataset/95274.csv?lang=no", 
    ";", escape_double = FALSE, locale = locale(encoding = "ISO-8859-1"), 
    trim_ws = TRUE)

whole_country <- read_delim("http://data.ssb.no/api/v0/dataset/95276.csv?lang=no", 
    ";", escape_double = FALSE, locale = locale(encoding = "ISO-8859-1"), 
    trim_ws = TRUE)



names(by_county) <- c("region","maaned","statistikkvariabel","pris") #Bytter navn for å unngå feil
names(whole_country) <- c("region","maaned","statistikkvariabel","pris") #Bytter navn for å unngå feil

kombinert <- merge(by_county,whole_country, by="maaned")

kombinert <- kombinert[ which(kombinert$pris.x > 0 ) , ] #Filtrer ut 0 
kombinert <- kombinert[ which(kombinert$pris.y > 0 ) , ] #Filtrer ut 0


#Filtrer ut kun prisene
kombinert_priser <- kombinert %>% filter(statistikkvariabel.x == 'Pris per rom (kr)') %>% filter(statistikkvariabel.y == 'Pris per rom (kr)')

mean(kombinert_priser$pris.x) #Gjennomsnittspris fylke gjennomsnitt
mean(kombinert_priser$pris.y) #Gjennomsnittspris hele landet


```


```{r fylker, warning = FALSE, echo = FALSE, message = FALSE}
#Lager en funksjon som lager gjennomsnittspris for hvert fylke
mean_fylker <- aggregate(pris.x ~ region.x, kombinert_priser, mean) 


#Filtrer ut kapasitet
kombinert_kapasitet <- kombinert %>% filter(statistikkvariabel.x == 'Kapasitetsutnytting av rom (prosent)') %>% filter(statistikkvariabel.y == 'Kapasitetsutnytting av rom (prosent)')

mean_kapasitet <- aggregate(pris.x ~ region.x, kombinert_kapasitet, mean) 

#Sammenheng mellom kapasitet og pris for alle fylker
cor.test(mean_fylker$pris.x,mean_kapasitet$pris.x) 

#Er en signifikant korrelasjon på 53% mellom kapasitet og pris

over_gjennomsnittet <- mean_fylker[ which(mean_fylker$pris.x > 757 ) , ] 
under_gjennomsnittet <- mean_fylker[ which(mean_fylker$pris.x < 757 ) , ] 


```

```{r Konklusjon}
#Fylke gjennomsnittspris er 741
#Gjennomsnittspris for hele landet er 757

#Over gjennomsnitt prisen for landet
#[1] "02 Akershus"         "03 Oslo"             "09 Aust-Agder"       "11 Rogaland"        
#[5] "12 Hordaland"        "14 Sogn og Fjordane" "21 Svalbard"         "50 Tr<U+00F8>ndelag"

#Under gjennomsnitt prisen for landet
#[1] "01 <U+00D8>stfold"                  "04 Hedmark"                        
#[3] "05 Oppland"                         "06 Buskerud"                       
#[5] "07 Vestfold"                        "08 Telemark"                       
#[7] "10 Vest-Agder"                      "15 M<U+00F8>re og Romsdal"         
#[9] "16 S<U+00F8>r-Tr<U+00F8>ndelag (-2017)" "17 Nord-Tr<U+00F8>ndelag (-2017)"  
#[11] "18 Nordland"                        "19 Troms - Romsa"                  
#[13] "20 Finnmark - Finnm<U+00E1>rku"    

#Det er en signifikant korrelasjon på 53% mellom kapasitet og pris
```


